name: CML-Test-1
#on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo "MODEL METRICS" 
          cat metrics.txt
          
          # Write your CML report
          echo "## MODEL METRICS" >>  report.md
          cat metrics.txt >> report.md
          echo "## MODEL Viz" >> report.md
          echo "### Feature importance" >> report.md
          cml-publish feature_importance.png --md >> report.md
          echo "### Residuals" >> report.md
          cml-publish residuals.png --md >> report.md
          
          cml-send-comment report.md

